### ISSUE TITLE
Installer stopped working / css not being applied

### ISSUE THREAD

**Issue by c133** [PhantomGamers/EnableNewSteamFriendsSkin#2]
Hello all,

With recent steam update, I am not able to apply my custom css to the friends list. I usually run the installer (Apr 12 installer) after each time steam updates to get my css back, but today I ran the installer and nothing happened, friends window css stayed as default steam. Is anyone else experiencing this, or just me?

Thank you.

**Comment by PhantomGamers** [comment]
Yeah I can confirm this is happening for me as well, I'll have to look into it when I have a chance. In the mean time, you can use the GUI version of the patcher which does still work: https://github.com/PhantomGamers/SteamFriendsPatcher/releases

**Comment by PhantomGamers** [comment]
Fixed in 942699e07d31eaea7c3006d3ecff4e7b7e9680ea
